name: Cypress E2E action
on: [pull_request]

jobs:
  build:
    name: Cypress E2E
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          config-file: cypress.config.js
